version: 2
jobs:
  build:
    working_directory: ~/8bit.biz
    docker:
      - image: mesosphere/aws-cli:latest
    environment:
      - AWS_S3_BUCKET_NAME: web.8bit.biz
    steps:
      - checkout
      - run:
          name: Deploy to S3 if branch is Master.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync ~/8bit.biz s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete --exclude='.git/*'
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

