version: 2
jobs:
  build:
    working_directory: ~/8bit.biz
    docker:
      - image: jksy/web.8bit.biz-build:latest
    environment:
      - AWS_S3_BUCKET_NAME: web.8bit.biz
    steps:
      - checkout
      - run:
          name: build & Deploy to S3.
          command: |
              cat index.slim | slimrb --pretty > index.html
              aws s3 sync ~/8bit.biz s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete --exclude='.git/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master

